<?output "../../web/js/index.js"?>
// This file was generated by PSTextMerge on =$today$= from
// Data File: =$datafilename$=
// Template: =$templatefilename$=
function randomQuote() {
  var quote = rand(10);
  switch(quote) {
  case 0:
    document.writeln('<blockquote class="pull">');
    document.writeln('<p><a href="elements/overview.html">');
    document.writeln('I think there was a gradual development by the boys, as they tried to make life a bit more interesting on record. They felt, &#8220;We don&#39;t have to go up onstage and do this; we can do it just for ourselves, and for the studio.&#8221; So it became a different kind of art form &#8212; like making a film rather than a live performance. That affected their thinking and their writing, and it affected the way I put it together, too.');
    document.writeln('</a></p>');
    document.writeln('<p class="author">');
    document.writeln('&#8212;&nbsp;George Martin, The Beatles&#8217; producer <br />');
    document.writeln('<a href="../closing/bibliography.html#beatles" target="biblio"><cite>The Beatles Anthology</cite></a>');
    document.writeln('</p>');
    document.writeln('</blockquote>');
    break;
  case 1:
    document.writeln('<blockquote class="pull">');
    document.writeln('<p><a href="elements/words.html">');
    document.writeln('I learned early on with Bob [Dylan] that the people he hung around with were not musicians. They were poets, like Allen Ginsberg. When we were in Europe, there&#8217;d be poets coming out of the woodwork. His writing came directly out of a tremendous poetic influence, a license to write in images that weren&#8217;t in the Tin Pan Alley tradition or typically rock &amp; roll, either. ');
    document.writeln('</a></p>');
    document.writeln('<p class="author">');
    document.writeln('&#8212;&nbsp;Robbie Robertson <br />');
    document.writeln('<a href="../closing/bibliography.html#robertson"><cite>Rolling Stone Magazine</cite></a>');
    document.writeln('</p>');
    document.writeln('</blockquote>');
    break;
  case 2:
    document.writeln('<blockquote class="pull">');
    document.writeln('<p><a href="elements/liberation.html">');
    document.writeln('For me the greatest pop music was music of liberation: Bob Marley, Bob Dylan, Elvis Presley, James Brown, Public Enemy, the Clash, the Sex Pistols. Those were pop groups that liberated an enormous amount of people to be who they are. (Springsteen 2003)');
    document.writeln('</a>');
    document.writeln('</p>');
    document.writeln('</blockquote>');
    break;
  case 3:
    document.writeln('<blockquote class="pull">');
    document.writeln('<p><a href="elements/records_in.html">');
    document.writeln('The trips to London introduced him to a second tier of musicians &#8212; Junior Wells, J. B. Hutto, Hound Dog Taylor &#8212; for whose work Dobell&#8217;s [record store] was the sole British outlet. Clapton also possessed a reel-to-reel Grundig tape recorder with which, night after night, he honed his technique. According to Rose Clapp&#8217;s son Adrian, &#8220;[Clapton] swore and cursed till he could copy the sounds exactly, from as many records as he could get hold of.&#8221; (Sandford 1999)');
    document.writeln('</a>');
    document.writeln('</p>');
    document.writeln('</blockquote>');
    break;
  case 4:
    document.writeln('<blockquote class="pull">');
    document.writeln('<p><a href="elements/records_out.html">');
    document.writeln('I was always slightly disappointed with all the performers I saw, from Little Richard to Jerry Lee. They never sound exactly like their records. I like &#8220;Whole Lotta Shakin&#8217;,&#8221; the 1956 take on the record, but I&#8217;m not interested in a variation on the theme. When Gene Vincent did &#8220;Be Bop A Lula&#8221; in Hamburg, he didn&#8217;t do it the same. It was a thrill to meet Gene Vincent and see him, but it was not &#8220;Be Bop A Lula.&#8221; I&#8217;m a record fan. ');
    document.writeln('</a></p>');
    document.writeln('<p class="author">');
    document.writeln('&#8212;&nbsp;John Lennon <br />');
    document.writeln('<a href="../closing/bibliography.html#beatles"><cite>The Beatles Anthology</cite></a>');
    document.writeln('</p>');
    document.writeln('</blockquote>');
    break;
  case 5:
    document.writeln('<blockquote class="pull">');
    document.writeln('<p><a href="closing/epilogue.html">');
    document.writeln('They were grown men who had climbed the mountain together, spoken to the gods, and returned to the valley, where they once again became mortal.');
    document.writeln('</a></p>');
    document.writeln('<p class="author">');
    document.writeln('&#8212;&nbsp;<cite>The Philadelphia Enquirer,</cite> writing about The Band <br />');
    document.writeln('<a href="../closing/bibliography.html#helm"><cite>This Wheel&#8217;s On Fire</cite></a>');
    document.writeln('</p>');
    document.writeln('</blockquote>');
    break;
  case 6:
    document.writeln('<blockquote class="pull">');
    document.writeln('<p><a href="elements/collaboration.html">');
    document.writeln('Young Rick was insistent. &#8220;Why can&#8217;t we have a band,&#8221; he asked, &#8220;where everybody plays an instrument, everybody sings, everybody does it without some guy out in front of the thing running the show and deciding the way things are gonna go?&#8221; This was a radical notion, like communism. But maybe, I thought, for the first time in our or anyone&#8217;s imagination, the rhythm section could run the band!');
    document.writeln('</a></p>');
    document.writeln('<p class="author">');
    document.writeln('&#8212;&nbsp;Levon Helm <br />');
    document.writeln('<a href="../closing/bibliography.html#helm"><cite>This Wheel&#8217;s On Fire</cite></a>');
    document.writeln('</p>');
    document.writeln('</blockquote>');
    break;
  case 7:
    document.writeln('<blockquote class="pull">');
    document.writeln('<p><a href="elements/electricity.html">');
    document.writeln('Around this time, the electric bass first started to come around. As soon as that hit, the whole rhythm section changed. With an electric bass, drums, guitar and piano, you had a full group. You had those two electric instruments, and they would sustain that bottom note. Like Scotty Moore, who played guitar with Elvis Presley. He&#8217;d be carrying along with his thumb and his pickin&#8217; finger on the bass strings and keeping the whole thing happening with lots of echo and reverb. And with his other fingers he&#8217;d be playing the melody. But when he wanted to stop and really bend those strings and make them cry and do what everybody likes to hear an electric guitar do, all of a sudden the bottom fell out. Now, with the electric bass carrying the load you could reach on up and grab your fill....');
    document.writeln('</a></p>');
    document.writeln('<p class="author">');
    document.writeln('&#8212;&nbsp;Levon Helm <br />');
    document.writeln('<a href="../closing/bibliography.html#weinberg"><cite>The Big Beat: Conversations with Rock&#8217;s Great Drummers</cite></a>');
    document.writeln('</p>');
    document.writeln('</blockquote>');
    break;
  case 8:
    document.writeln('<blockquote class="pull">');
    document.writeln('<p><a href="elements/big_beat.html">');
    document.writeln('[David] Susskind invited Phil Spector to the <cite>Open End</cite> television program one evening to &#8220;talk about the record business.&#8221; Suddenly Susskind and &#8220;William B.&#8221; [Williams], station WNEW&#8217;s old-nostalgia disc jockey, were condemning Spector as some kind of sharpie poisoning American culture.... Susskind and Williams kept throwing Spector&#8217;s songs at him.... And Susskind sits there on the show reading one of Spector&#8217;s songs out loud, no music, just reading the words, from the Top Sixty or whatever it is, &#8220;Fine Fine Boy,&#8221; to show how banal rock&#8217;n roll is. The song just keeps repeating &#8220;He&#8217;s a fine fine boy.&#8221; So Spector starts drumming on the big coffee table there with the flat of his hands in time to Susskind&#8217;s voice and says, &#8220;What you&#8217;re missing is the beat.&#8221;');
    document.writeln('</a></p>');
    document.writeln('<p class="author">');
    document.writeln('&#8212;&nbsp;Tom Wolfe <br />');
    document.writeln('<a href="../closing/bibliography.html#wolfe"><cite>The Kandy-Kolored Tangerine-Flake Streamline Baby</cite></a>');
    document.writeln('</p>');
    document.writeln('</blockquote>');
    break;
  case 9:
    document.writeln('<blockquote class="pull">');
    document.writeln('<p><a href="elements/basics.html">');
    document.writeln('Mitch Murray was writing songs. He came up with &#8220;How do you do it? How do you do what you do to me?&#8221; We listened to the demo and said, &#8220;It&#8217;s a hit, George, but we&#8217;ve got a song, &#8216;Love Me Do.&#8217;&#8221; George said, &#8220;I don&#8217;t think yours is such a big hit.&#8221; We said, &#8220;Yes, but it is <i>us,</i> and it is what we&#8217;re about.&#8221; (Beatles 2000)');
    document.writeln('</a>');
    document.writeln('</p>');
    document.writeln('</blockquote>');
    break;
  default:
    document.writeln('<blockquote class="pull">');
    document.writeln('<p><a href="elements/overview.html">');
    document.writeln('I think there was a gradual development by the boys, as they tried to make life a bit more interesting on record. They felt, &#8220;We don&#39;t have to go up onstage and do this; we can do it just for ourselves, and for the studio.&#8221; So it became a different kind of art form &#8212; like making a film rather than a live performance. That affected their thinking and their writing, and it affected the way I put it together, too.');
    document.writeln('</a></p>');
    document.writeln('<p class="author">');
    document.writeln('&#8212;&nbsp;George Martin, The Beatles&#8217; producer <br />');
    document.writeln('<a href="../closing/bibliography.html#beatles" target="biblio"><cite>The Beatles Anthology</cite></a>');
    document.writeln('</p>');
    document.writeln('</blockquote>');
    break;
  }           
}
function makeArray(len) {
}
var size = 200;
var ix = 0;
var album = new Array();
var artist = new Array();
<?nextrec?>
album[ix] = "=$image_name$=";
artist[ix] = "=$artist_link$=";
ix++
<?loop?>
var max = ix;
function rand(n) {
  seed = (0x015a4e35 * seed) % 0x7fffffff;
  return (seed >> 16) % n;
}
var now = new Date();
var seed = now.getTime() % 0xffffffff;


